### ISSUE TITLE
I have the following error warning after trying to run parsnp

### ISSUE THREAD

**Issue by sebastianguenther** [marbl/harvest-tools#6]

**Comment by sebastianguenther** [comment]
imt@imt-Latitude-E6430:~/Arbeitsfläche/Parsnp-Linux64-v1.1$ ./parsnp -d ST648 -r ! -c
|--Parsnp v1.1--|
For detailed documentation please see --> http://harvest.readthedocs.org/en/latest

<<Parsnp started>>

-->Reading Genome (asm, fasta) files from ST648..
  |->[OK]
-->Reading Genbank file(s) for reference (.gbk) ..
  |->[WARNING]: no genbank file provided for reference annotations, skipping..
-->Running Parsnp multi-MUM search and libMUSCLE aligner..
**ERROR**
The following command failed:
>>/tmp/_MEIvPTxGS/parsnp /home/imt/Arbeitsfläche/Parsnp-Linux64-v1.1/P_2015_03_02_061225798420/parsnpAligner.ini
Please veryify input data and restart Parsnp. If the problem persists please contact the Parsnp development team.
**ERROR**
What could be the problem? thnks

**Comment by treangen** [comment]
hi Sebastian,

>What could be the problem? thnks

Thanks for sending this, I had a look into your error and it is a parsnp binary packaging issue (of libMuscle, causing the multi-alignment step to fail) affecting the Harvest v1.1 Linux 64-bit binary release. 

I've updated this parsnp binary with properly packaged dependencies (https://github.com/marbl/parsnp/releases/download/v1.1/Parsnp-Linux64-v1.1.tar.gz), and will post an updated Harvest v1.1.1 release today that includes this fix.

Please give this binary a try & let me know if you run into any issues.

**Comment by sebastianguenther** [comment]
hi todd,
thanks you that was quick! and it works right now..thank you very much again!
seb
